services:
  mas-portal-api-dev:
    container_name: nest-api-deployee
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
    profiles:
      - development